name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12"]
    name: Node ${{ matrix.node }} eslint run
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install eslint
        run: npm install eslint
      - name: Lint
        run: make lint
